### ISSUE TITLE
Day 8: Dictionaries and Maps A lot of solution does not works.

### ISSUE THREAD

**Issue by sergioluevanoss** [xeoneux/30-Days-of-Code#107]
The solution doesn't works.

My solution for python.
[sergiosolution;).txt](https://github.com/xeoneux/30-Days-of-Code/files/3319697/sergiosolution.txt)

**Comment by mfirmanakbar** [comment]
i think better using `n.times do` to replace `for x in 0..n-1` because you dont need variable x 
*cmiiw

**Comment by xeoneux** [comment]
@sergioluevanoss @mfirmanakbar could you please provide PRs with the update? 😄

**Comment by ayushmanbh** [comment]
There are unknown number of queries so this solution is wrong.
