### ISSUE TITLE
Issue with 30-Days-of-Code/8 - Dictionaries and Maps/Solution.py 

### ISSUE THREAD

**Issue by APratham** [xeoneux/30-Days-of-Code#186]
I am facing a problem with trying to execute the Python code. It gives me a Runtime Error on Hackerrank. I couldn't understand what could have caused it. I even tried evaluating the case which threw the Runtime Error but I couldn't find anything wrong. The code doesn't have any errors too.

**Comment by xeoneux** [comment]
Hi @APratham 
Would you please create a PR with the latest Python code that works? 😄

**Comment by APratham** [comment]
I had actually just posted the solution using another language. It will require some time for me to write the Python code and see if it works, but I will do it.
