### ISSUE TITLE
please explain the line

### ISSUE THREAD

**Issue by sam2702** [xeoneux/30-Days-of-Code#19]
**maximum=-9*7**

**Comment by xeoneux** [comment]
Please specify the language and the day

**Comment by sam2702** [comment]
**Language:Python
Day :12**

**Comment by xeoneux** [comment]
Since there are 7 elements that make up the hourglass shape and the minimum value for each element is -9, we take `-9 * 7`, or -63, as the minimum (or maximum) value possible for each hourglass.

And then set the maximum value accordingly if it's greater that this value.
