### ISSUE TITLE
Python Day 6

### ISSUE THREAD

**Issue by freedompraise** [xeoneux/30-Days-of-Code#222]
The Let's review solution for python keeps breaking at line 3
The code requires more input than provided by stDIN.
The code breaks when you try to initialize "NumberOfStrings" input variable as an integer which gives an error as an alphabet cannot be conerted to an integer  

The solution is to take out the "NumberOfStrings" variable.
Solution in next commment👇

 `

`

**Comment by freedompraise** [comment]
`N = int(input())
# First we have to take the input of the number of Strings 

# for loop from 0 to the length of the String

for i in range(0,):

    # Taking input from the User 

    string = input()

    # The below line has two parts 1. string[::2] & 2. string[1::2].
    # General format is [start:stop:step].
    # 1. string[::2] basically means that start from 0 to the end of the String skipping 2 characters hence taking all even strings 
    # 2. string[1::2] same as the above but we start from 1 and not 0 

    print(string[::2],string[1::2])

`

**Comment by xeoneux** [comment]
Hey @freedompraise, can you create a PR for the same? Thanks!

**Comment by freedompraise** [comment]
Okay, I will work on that now
