### ISSUE TITLE
Add 7 - Arrays for TypeScript

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#26]
**Task:** Add solution for 7 - Arrays task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in TypeScript language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in TypeScript language and create a Pull Request for the same. 😄

**Comment by gmontalvo404** [comment]
Can i do this?

**Comment by xeoneux** [comment]
Sure thing!

**Comment by gmontalvo404** [comment]
Ready!

**Comment by gmontalvo404** [comment]
Ready!
there is a problem with the folder '0 - Hello, world'.
