### ISSUE TITLE
Add 8 - Dictionaries and Maps for Kotlin

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#28]
**Task:** Add solution for 8 - Dictionaries and Maps task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in Kotlin language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in Kotlin language and create a Pull Request for the same. 😄

**Comment by shaharukhs** [comment]
Updated Swift Code for Swift 4 and above
```
    // read contacts into phone book
    var contact = readLine()!.split(separator: " ").map(String.init)
    phoneBook[contact[0]] = Int(contact[1])
```

**Comment by xeoneux** [comment]
Could you please make a PR for the same @shaharukhs? 😄

**Comment by phonj** [comment]
Can i do this ?

**Comment by xeoneux** [comment]
Sure!

**Comment by rusyasoft** [comment]
Here is my PR please check it https://github.com/xeoneux/30-Days-of-Code/pull/118
