### ISSUE TITLE
Add 8 - Dictionaries and Maps for TypeScript

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#29]
**Task:** Add solution for 8 - Dictionaries and Maps task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in TypeScript language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in TypeScript language and create a Pull Request for the same. 😄

**Comment by marcospds** [comment]
Create pullrequest #115 for this issue.
