### ISSUE TITLE
Add B - Binary Numbers for TypeScript

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#33]
**Task:** Add solution for B - Binary Numbers task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in TypeScript language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in TypeScript language and create a Pull Request for the same. 😄

**Comment by marcospds** [comment]
Create pullrequest #114 for this issue.
