### ISSUE TITLE
Add F - Abstract Classes for Kotlin

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#38]
**Task:** Add solution for F - Abstract Classes task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in Kotlin language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in 
Kotlin language and create a Pull Request for the same. 😄

**Comment by noble-gas** [comment]
Added the solution, check it.
