### ISSUE TITLE
Day 28 Java code is incorrect!

### ISSUE THREAD

**Issue by Kvaibhav01** [xeoneux/30-Days-of-Code#5]
The Java code that you provided [here ](https://github.com/xeoneux/30-Days-of-Code/blob/master/X%20-%20RegEx%2C%20Patterns%2C%20and%20Intro%20to%20Databases/Solution.java)is not accepted by HackerRank compiler. 

I have written another [Java code](https://github.com/Kvaibhav01/HackerRank-in-Java/blob/master/30%20Days%20of%20Code%20Challenges/Day%2028-%20RegEx-%20Patterns-%20and%20Intro%20to%20Databases/Regex.java) which is acceptable. Please correct that!

**Comment by xeoneux** [comment]
Hey @Kvaibhav01, I'm compiling using Java 8 instead of Java 7. Try that, it'll run!

**Comment by Kvaibhav01** [comment]
Okay, got it!
