### ISSUE TITLE
Add C - 2D Arrays for Ruby

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#60]
**Task:** Add solution for C - 2D Arrays task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in Ruby language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in Ruby language and create a Pull Request for the same. 😄

**Comment by ibrahimelbanna** [comment]
@xeoneux  I have added solution for this problem I hope it get merged 
https://github.com/xeoneux/30-Days-of-Code/pull/97
