### ISSUE TITLE
Add F - Abstract Classes in Ruby

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#62]
**Task:** Add solution for F - Abstract Classes task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in Ruby language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in Ruby language and create a Pull Request for the same. 😄

**Comment by ibrahimelbanna** [comment]
https://github.com/xeoneux/30-Days-of-Code/pull/99
