### ISSUE TITLE
Add G - Scope in Ruby

### ISSUE THREAD

**Issue by xeoneux** [xeoneux/30-Days-of-Code#63]
**Task:** Add solution for G - Scope task at [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) by HackerRank in Ruby language.

**Process:** Register at https://www.hackerrank.com and then figure out the mentioned task for [30 Days of Code](https://www.hackerrank.com/domains/tutorials/30-days-of-code) in Ruby language and create a Pull Request for the same. 😄

**Comment by ibrahimelbanna** [comment]
Ruby language is not supported for this problem

**Comment by Miftahunajat** [comment]
Hey i would like to work on this issue
